### ISSUE TITLE
Concerning the future of Itchy

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-ionic#1]
@micahlt Please tell us what you're up to with this new app. I'm sorry if you said already said anything about it on Teams - I don't check it often. But I'd guess you didn't

**Comment by micahlt** [comment]
Apologies - I commented on your Scratch profile but I realized that you don't check that often.  I'm rebuilding Itchy with Ionic Vue. 😳 I've finally realized the benefits of doing things the right way over doing things the easy way.  The codebase for  `itchy-cordova` is a mess, and I can see now that doing everything in vanilla JS isn't always optimal.  I know this (restarting, kinda) is frustrating.  Believe me, I don't _want_ to - I've spent hours working on the Cordova and JS version.  Probably more than anyone on the team.  I'm sincerely sorry that I sorta wasted everyone's time with `itchy-cordova`.  However, a lot of the functional code can be copied over to `itchy-ionic`.  I'm fully open to your opinions @locness3 @Scratch-Client-4/everyone

**Comment by locness3** [comment]
Oh, I do check my Scratch profile but I didn't in the last days. Also remember that out of the 17 people here, mostly nobody's actually active - aside from you and me; not sure much people wasted time.
I'm glad you're doing things the "right" way. 
While I'm here, I should say what I expect of the app - and would appreciate if @Scratch-Client-4/everyone did the same so we can commonly agree on what we should do.
What I expect of a Scratch mobile app is to stay in touch with the community - see what's happening on your profile, projects, studios, forum threads, and what people you're following are up to, and potentially checking frontpaged projects. This implies, first and foremost, allowing to sign in to the website with a Scratch account - and I would make this a priority. I already tried  reproducing the same requests as I could find in the devtools on Scratch in Postman but wasn't able to get any token back. Then a great Messages screen - I like the way the Scratch Messaging Extension and ScratchAddons does it, we could possibly borrow some code there. Finally, a seperate Feed screen equivalent to the What's Happening box on the Scratch website  but that would be more like a Twitter stream.
This is what I'd like as a mobile Scratch client - but I likely don't represent the majority of users, and I don't use Scratch much anymore (I also think the above is the same for you @micahlt). That's why I'm hoping other people would tell us what they expect - maybe ask directly on Scratch?

Side note : making a native app with ionic uses cordova.

**Comment by Mai-Trys** [comment]
I really don’t have the skills to do much than visual work. That being
design and CSS. I am active on Scratch if you would like to contact me
there, you can see some of my work.

**Comment by Mai-Trys** [comment]
Let it be known I’m pretty busy as A High School student but I’d be happy to assist on the visual front as I would like to get more involved. So If you want to assign me to something (i.e advancing the website) go ahead.

**Comment by bryn-trys** [comment]
Anyways, on my opinions on the app, I can’t say much for the internal workings but I do believe that the UI should reflect the web version, so making sure to format everything is a priority. Using Scratch on mobile is pretty buggy so if we’re recycling code we will need to address that. In terms of what I want to see on the app, what Micha and Locness suggested sounds just fine, maybe with the addition of a block alternative? I’ve been thinking that Scratch should have the option to be able to code in JavaScript/Python along with the blocks, what do you think on this? My biggest hope for the app is a messaging and collaboration system though. To be able to talk and work on projects would be a big help. And to help small Scratchers get noticed, the Twitter stream idea is great, but maybe also a functional hashtag system? You can “subscribe” to certain tags and get a feed of the projects you’re interested in. This can help Scratchers get noticed by their target audience and also create a brand for themselves. Finally, I feel like communication is a bit lax here, do you think it would be helpful to create a Discord? I have experience setting up servers pretty fast so I can make one if people are interested. (P.S sorry for rambling and commenting so much, just wanted to make my stance in the project clear since I’ve been AFK for so long).

**Comment by micahlt** [comment]
> Oh, I do check my Scratch profile but I didn't in the last days. Also remember that out of the 17 people here, mostly nobody's actually active - aside from you and me; not sure much people wasted time.
> I'm glad you're doing things the "right" way.
> While I'm here, I should say what I expect of the app - and would appreciate if @Scratch-Client-4/everyone did the same so we can commonly agree on what we should do.
> What I expect of a Scratch mobile app is to stay in touch with the community - see what's happening on your profile, projects, studios, forum threads, and what people you're following are up to, and potentially checking frontpaged projects. This implies, first and foremost, allowing to sign in to the website with a Scratch account - and I would make this a priority. I already tried reproducing the same requests as I could find in the devtools on Scratch in Postman but wasn't able to get any token back. Then a great Messages screen - I like the way the Scratch Messaging Extension and ScratchAddons does it, we could possibly borrow some code there. Finally, a seperate Feed screen equivalent to the What's Happening box on the Scratch website but that would be more like a Twitter stream.
> This is what I'd like as a mobile Scratch client - but I likely don't represent the majority of users, and I don't use Scratch much anymore (I also think the same goes for you @micahlt). That's why I'm hoping other people would tell us what they expect - maybe ask directly on Scratch?
> 
> ~Side note : making a native app with ionic uses cordova.~ Didn't know about Capacitor at the time.

You think a lot like me!  😄 Yes, this is nearly exactly what I'm aiming for.  Right now I'm definitely focusing on the following: 
 - Project rendering
 - Login functionality
 - Commenting on projects and profiles
 - Implementing a custom studio API (via [`micahlt/itchy-api`](https://github.com/micahlt/itchy-api))

The main issues we're going to run into are the old parts of the site (like studios) that are still using `XMLHttpRequest` with forms, which makes them slightly hard to implement.  Communicating with those parts of the site and adding login functionality are our top priorities.

**Comment by micahlt** [comment]
@bryn-trys Thanks for the suggestions!  Unfortunately, most of those are currently out of the scope of what we're doing with Itchy v1.   
>Finally, I feel like communication is a bit lax here, do you think it would be helpful to create a Discord?

The only reason why we don't have a Discord server is that my parents will not let me use Discord.  Y'all are welcome to make one - it's just that I'm (no offense to anyone) the primary developer, and I can't have it 😳

**Comment by micahlt** [comment]
@bryn-trys We do have a (slightly dead) Gitter chat that we should use more often: https://gitter.im/scratchclient4/community

**Comment by bryn-trys** [comment]
> @bryn-trys We do have a (slightly dead) Gitter chat that we should use more often: https://gitter.im/scratchclient4/community

Oh, alright! For me, I communicate pretty well on Discord. Right now, I’m a little preoccupied because my freaking README isn’t working 😭 so I’ll get back to you in a little bit

**Comment by bryn-trys** [comment]
Alright I think I’ll join the Gitter

**Comment by YOYITsM3M8** [comment]
> @bryn-trys Thanks for the suggestions!  Unfortunately, most of those are currently out of the scope of what we're doing with Itchy v1.   
> 
> >Finally, I feel like communication is a bit lax here, do you think it would be helpful to create a Discord?
> 
> 
> 
> The only reason why we don't have a Discord server is that my parents will not let me use Discord.  Y'all are welcome to make one - it's just that I'm (no offense to anyone) the primary developer, and I can't have it 😳 

I'm pretty sure we have one?

**Comment by bryn-trys** [comment]
> > @bryn-trys Thanks for the suggestions!  Unfortunately, most of those are currently out of the scope of what we're doing with Itchy v1.
> > > Finally, I feel like communication is a bit lax here, do you think it would be helpful to create a Discord?
> > 
> > 
> > The only reason why we don't have a Discord server is that my parents will not let me use Discord.  Y'all are welcome to make one - it's just that I'm (no offense to anyone) the primary developer, and I can't have it 😳
> 
> I'm pretty sure we have one?

If we do, can you link it here?

**Comment by Semisol** [comment]
I have not been active lately. What is going on?

**Comment by locness3** [comment]
There is a Discord ([and I tried ensuring y'all were aware of it](https://github.com/orgs/Scratch-Client-4/teams/everyone/discussions/18)).

**Comment by locness3** [comment]
..the invite there is invalid. @githubfan, as you're the Discord's owner, can you make a new one? Even better, could you use smth like https://invite.gg to have a custom link?

**Comment by locness3** [comment]
> I feel like communication is a bit lax here

Just to make sure: when I ping @Scratch-Client-4/everyone in a Github Team discussion, do y'all see it? Normally yes, but it looks like not really.

**Comment by micahlt** [comment]
@locness3 Yes, we do, and I get emails so don't ping so much lol (jk ofc, you're fine)

**Comment by micahlt** [comment]
I'm closing this issue :smile:
