### ISSUE TITLE
Where do the release names come from?

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-ionic#10]
Also suggesting we could name it after famous (or underrated) Scratchers.

**Comment by micahlt** [comment]
Currently codenames come from https://killercup.github.io/codenamer/.  I'm willing to consider Scratch-related names, but I'd rather not name releases after Scratchers (because that makes the team seem biased).

**Comment by locness3** [comment]
Huh.

**Comment by monitrr** [comment]
![image](https://user-images.githubusercontent.com/36968271/107889198-cfb37c00-6f08-11eb-86d1-d53885eb843b.png)
I think these settings sound best

**Comment by micahlt** [comment]
Can this issue be closed @locness3?
