### ISSUE TITLE
Write up a privacy policy

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-ionic#11]
@micahlt, you mean "your password is only sent to Scratch" right?

**Comment by micahlt** [comment]
@locness3 Not directly, no.  To avoid CORS restrictions the username and password have to be sent to the itchy-api server and from there to Scratch.

**Comment by locness3** [comment]
might want to emphasize we don't store it (and write an actual privacy policy)

**Comment by micahlt** [comment]
You're right - this is high priority.  Would you like to draft one?

**Comment by locness3** [comment]
"high priority"  
adds an "enhancement" label

**Comment by locness3** [comment]
> You're right - this is high priority. Would you like to draft one?

I don't really know how the app works - not able to run it yet - so not yet

**Comment by micahlt** [comment]
Wait, you do know that you can run the app with`ionic serve`… right?  Unless you're going to bundle for Android directly, there's no need to actually use Android Studio.

**Comment by locness3** [comment]
thx for the info

**Comment by locness3** [comment]
![image](https://user-images.githubusercontent.com/37651007/107149633-f0546280-6959-11eb-8760-2fa5e6c51b9f.png)
Well yes, but actually no

**Comment by micahlt** [comment]
What on earth ~ you may need to reclone the repo - it looks like you may be missing some files ;-;

**Comment by micahlt** [comment]
@locness3 Wait no - I think I fixed it.  Let me push the fix and you can fetch and pull.

**Comment by micahlt** [comment]
@locness3 Please fetch and pull now, then tell me if the Android build config and the `ionic serve` issues are fixed.

**Comment by locness3** [comment]
Yes! That works. Tysm!

**Comment by micahlt** [comment]
No problem!  Now, time to mark all of these posts as off-topic...

**Comment by micahlt** [comment]
Resolved by Scratch-Client-4/landing#25.
