### ISSUE TITLE
How to run on Android?

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-ionic#12]
I know I'm supposed to hit the "Run" button in Studio, but there are no run configs in the project, so it doesn't really work.

**Comment by micahlt** [comment]
What do you mean by run configs?  It works fine for me - just run `npm run production` and then hit the play button.

**Comment by locness3** [comment]
Run configs, the thing in Android studio that determines what to do when you hit the Play button. Go to Run > Edit Configurations and check "Store as project file" so it gets committed to the project. Without any the Play button is disabled (i ran `npm run production`)

**Comment by micahlt** [comment]
Ah, yes!  I just used the built-in "Android App" preset - see below: 
![image](https://user-images.githubusercontent.com/28816297/107127858-9af75300-687e-11eb-9849-226eb83161a4.png)

**Comment by locness3** [comment]
So just check "SHare through VCS" :)

**Comment by locness3** [comment]
When I go to create a config, somehow it just shows me "no module".

**Comment by micahlt** [comment]
> So just check "Share through VCS" :)

I'll work on that right now 👍

**Comment by locness3** [comment]
Fixed in https://github.com/Scratch-Client-4/itchy-ionic/commits/master
