### ISSUE TITLE
[bug] No error on 404 project pages

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/itchy-ionic#13]
If the user is not connected to the internet or a project is not found, the app simply breaks.  We need 404 and 503 errors generated so that the user can see what is wrong!

**Comment by locness3** [comment]
503? more just a "the internet is offline"

**Comment by micahlt** [comment]
> 503? more just a "the internet is offline"

You know what I mean lol - just errors to handle those sort of codes.

**Comment by micahlt** [comment]
@locness3 didn't you add this earlier?

**Comment by locness3** [comment]
No

**Comment by micahlt** [comment]
Ah, okay, nevermind

**Comment by micahlt** [comment]
Fixed in cb6c41d8fb244185fa8f24f22b6be4d14431ae7a.
