### ISSUE TITLE
Cannot read property intentShim of undefined

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-ionic#14]
Running `ionic serve` works, but the app can't run within the browser. Nothing happens. The console shows :
```
Uncaught (in promise) TypeError: Cannot read property 'intentShim' of undefined
    at Proxy.created (App.vue?3dfd:40)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
    at callSyncHook (runtime-core.esm-bundler.js?5c40:5898)
    at applyOptions (runtime-core.esm-bundler.js?5c40:5829)
    at finishComponentSetup (runtime-core.esm-bundler.js?5c40:6507)
    at setupStatefulComponent (runtime-core.esm-bundler.js?5c40:6440)
    at setupComponent (runtime-core.esm-bundler.js?5c40:6380)
    at mountComponent (runtime-core.esm-bundler.js?5c40:4118)
    at processComponent (runtime-core.esm-bundler.js?5c40:4094)
```
I assume it is trying to use a native API?

**Comment by micahlt** [comment]
You're correct - intentShim is a Cordova API for Android wrapped by Capacitor.  The documentation for the plugin can be found [here](https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent) while the meager docs for the Capacitor installation can be found [here](https://ionicframework.com/docs/native/web-intent/).  To install, run: 

```bash
ionic cordova plugin add com-darryncampbell-cordova-plugin-intent
npm install @ionic-native/web-intent
```

However, if this problem only occurs in the browser (e.g., running `npm run production` and running the app on Android works without errors), you may need to add an `if` statement with [platform detection](https://ionicframework.com/docs/vue/platform) to ensure that the plugin is only used on Android.

**Comment by locness3** [comment]
> you may need to add an if statement with platform detection to ensure that the plugin is only used on Android.

I think that's what's needed

**Comment by micahlt** [comment]
All right - I'm planning on developing a little bit more this afternoon (Central Standard Time), so I'll implement that.

**Comment by micahlt** [comment]
Confirmed - this is a reproducible issue.  I'm working on it now.

**Comment by micahlt** [comment]
Fixed in 699bef4afc6c1c3ffa8b6f235310e44cca733899.

**Comment by locness3** [comment]
Thanks!

**Comment by locness3** [comment]
BTW, quick tip : use `ionic lab` :) (make sure to say `y` to install the thing, even if webpack's messages get on top of the prompt)

**Comment by micahlt** [comment]
Will do 👍
