### ISSUE TITLE
Slow down Micah

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-ionic#18]
I understand you might want a fast development, but please keep quality in mind.
The all-new 0.5.0 release has ridiculous "known issues", that should be fixed before making the release. I know this is alpha software, but breaking the whole app by navigating to a page, seriously... Pretty sure you just forgot to add a " if the user is logged in" check.

@micahlt

**Comment by locness3** [comment]
How did I even close this

**Comment by monitrr** [comment]
sorry for necro but lol

**Comment by micahlt** [comment]
Okay, yeah, sorry.  I'm going too fast.  I'll try to see if I can work on those bugs before the next feature addition.

**Comment by locness3** [comment]
I did work on the first one https://github.com/Scratch-Client-4/itchy-ionic/commit/ee1d0c9a0042807ef087d393b5ad36205d42a2cd

**Comment by micahlt** [comment]
And I just fixed the UX for the messages (#23)

**Comment by locness3** [comment]
saw it, will test
