### ISSUE TITLE
Turbowarp iframe white background in dark mode

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/itchy-ionic#2]
On the web, `iframe` elements that display the Turbowarp embed display a white background when the app is in dark mode.  This is not an issue with Turbowarp itself since on Android everything works correctly.  See below: 

<img src="https://user-images.githubusercontent.com/28816297/105060812-73ab2400-5a3e-11eb-8efa-8cd7ab0dba71.png" width="200px"></img>

**Comment by monitrr** [comment]
I found out how to apply css to iframes

**Comment by locness3** [comment]
congratz

**Comment by monitrr** [comment]
:(

**Comment by monitrr** [comment]
whenever i build the app in android studio i get an error

**Comment by micahlt** [comment]
@monitrr What's the error message from Android Studio?  Can you paste a screenshot?

> I found out how to apply css to iframes

Unfortunately, this isn't a CSS issue since Turbowarp embeds act fine in `itchy-cordova` as well as when `itchy-ionic` is run on Android.

**Comment by locness3** [comment]
> whenever i build the app in android studio i get an error
pls create a seperate issue

**Comment by locness3** [comment]
@micahlt On what browser?

**Comment by micahlt** [comment]
Closing this because I've looked and cannot find a solution.  Plus we're not really going to publish the browser version of Itchy, just the mobile.
