### ISSUE TITLE
Stop. Pushing. To. Master. Use. Develop. Branches. Please.

### ISSUE THREAD

**Issue by Semisol** [Scratch-Client-4/itchy-ionic#21]

**Comment by Semisol** [comment]
please micah stop

**Comment by Semisol** [comment]
If possible, can you do this:
1. make feature branch for your additions
2. merge to develop (squash if too long history for one feature)
3. rebase develop to master

**Comment by locness3** [comment]
@micahlt

**Comment by Semisol** [comment]
> @micahlt. Although idk about using a development branch, i completely agree to making PRs at some point, mostly so we can hear back from the "community".

Master is RELEASE READY, at least from the perspective of me and Kenny2github (not mentioned) with the ScratchVerifier project. It really makes our job easier and one reasons is automatic deployment. Mostly, it is this:
1. Feature issue
2. Development
3. PR
4. Code review
5. Master push
6. Servers update SV version

**Comment by locness3** [comment]
Not all projects should work the same

**Comment by Semisol** [comment]
> Not all projects should work the same

I know, just that it could work that way.
I plan this:
1. Feature branches by people to develop (Squash for single feature + long history, otherwise merge commit)
2. `develop` commits must not be made except things that are too small.
3. `develop` is REBASED to `master`, and `master` is not directly written to.
4. Every `master` rebase will indicate mostly a (pre)release

**Comment by locness3** [comment]
maybe

@micahlt

**Comment by micahlt** [comment]
@locness3 @Semisol Yes, we need more structure.  The only reason I've been pushing to `master` is that I've been the only contributor as far as code goes for several months.  I'm not familiar with rebase since SC4 is the first large-scale project I've worked on - I'll do some research and see if I can figure it out.  Is there a way to do it with GitHub.com/Desktop or is it only CLI?

**Comment by Semisol** [comment]
Rebasing is essentially setting the branch tip to the previous branch.

**Comment by Semisol** [comment]
So essentially, setting `master` to be at the same commit as `develop`

**Comment by micahlt** [comment]
Cool - I know there's a `git rebase` command - any GUI on GitHub for that or just CLI?

**Comment by Semisol** [comment]
> Cool - I know there's a `git rebase` command - any GUI on GitHub for that or just CLI?

Github has that feature

**Comment by micahlt** [comment]
Sounds good - I'm closing this issue.
