### ISSUE TITLE
Messages button UX

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-ionic#23]
Currently, if the user is signed out, pressing Messages opens Scratch's messages page in the browser.

Considering you can sign in to the app to view your messages, I think we should make it more obvious in this case, and redirect the user to log in to the app. And, add a "view in browser" link to the messages page.

What do you think? @Scratch-Client-4/everyone

**Comment by micahlt** [comment]
Ah, that makes much more sense.  Yeah, let's go with that.  Since there have been no other comments I'll just make the executive decision and say yeah.

**Comment by Semisol** [comment]
+1

**Comment by micahlt** [comment]
Implemented in 1bb1d9ec7a0299e650562661359dfc7cb91904ed.
