### ISSUE TITLE
[bug] `forumpost` and `curatorinvite` message types aren't correctly handled

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-ionic#24]
The `forumpost` (when there's a new post in a forum thread) and `curatorinvite` message type (when you get invited to a studio) message types aren't correctly handled by MessagesPage and just show the person username.
Obviously we should properly handle it, but I think we may also want to add a fallback like "did something (${type})" for unknown message types.

Progress:
- [x] `curatorinvite`
- [ ] `forumpost`

**Comment by micahlt** [comment]
This makes sense - however, I'm not sure we'll need a fallback since there are a fixed amount of message types (unless Scratch Team decides to make a massive API change).

**Comment by locness3** [comment]
Bump.

**Comment by micahlt** [comment]
> Bump.

Unless I'm provided a message object for these types, I can't work on this issue.

**Comment by locness3** [comment]
Follow a forum thread, and ask someone to put you in a studio.

**Comment by micahlt** [comment]
> Follow a forum thread, and ask someone to put you in a studio.

I'll work on this, I just haven't had time so far.

**Comment by micahlt** [comment]
#37 Resolves `curatorinvite` messages.

**Comment by micahlt** [comment]
#46 will add `forumpost` messages.
