### ISSUE TITLE
Support login to Scratch

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/itchy-ionic#3]
One of the core features missing from both `itchy-cordova` and `itchy-ionic` is login functionality.  We need to figure out the API endpoints for retrieving a user token and how to use that token, as soon as possible.  Help on this is greatly appreciated.

**Comment by micahlt** [comment]
We might could implement @Zxnii's solution [here](https://github.com/Zxnii/scratch-site-api/blob/85dec285d9bd5c32b179613e0bc6cf05000ee6aa/index.js#L31) - it seems relatively simple and up-to-date.

**Comment by micahlt** [comment]
And if we run into CORS issues here, we could consider running a Node VM to make the requests underneath the Ionic app with [this library](https://code.janeasystems.com/nodejs-mobile/getting-started-cordova).

**Comment by locness3** [comment]
From what I see where you linked, we need to set cookies for the CSRF token - completely forgot about that in my testing - which is definitely impossible in a webview with a cross-origin alone.

**Comment by locness3** [comment]
Wait, you linked to a tutorial for Cordova - we don't use this, right?

**Comment by AyzansAlt** [comment]
Why can't we use Scratch Verifier / SV2

**Comment by AyzansAlt** [comment]
> We might could implement @Zxnii's solution [here](https://github.com/Zxnii/scratch-site-api/blob/85dec285d9bd5c32b179613e0bc6cf05000ee6aa/index.js#L31) - it seems relatively simple and up-to-date.

If you didn't already see this:
`const Scratch = require("scratch-site-api")
const user = new Scratch.User()

async function main() {
    await user.login("username", "password")

    console.log(await user.getSession().json)
}`

**Comment by locness3** [comment]
> Why can't we use Scratch Verifier / SV2

... This has already been discussed

**Comment by locness3** [comment]
> If you didn't already see this:

Ofc, we could use the scratch-site-api module

**Comment by monitrr** [comment]
> > Why can't we use Scratch Verifier / SV2
> 
> ... This has already been discussed

where

**Comment by locness3** [comment]
[I'm tired of this](https://www.notion.so/locness/Recap-Logging-in-to-Scratch-in-SC4-a57d5f44d7aa425698bd619e1fd97773)

**Comment by monitrr** [comment]
i wish scratch had an api

**Comment by locness3** [comment]
It does! It just lacks documentation as it is mostly designed for scratch's internal use. How would be fetching data from scratch otherwise?

**Comment by monitrr** [comment]
oh, im stupid, i mean't an api ~~that was actually useful~~ that was good

**Comment by micahlt** [comment]
This has been implemented in commit e71b53a90c13950c7faca9aa338a12470907fc84.

**Comment by locness3** [comment]
Congrats! :rocket:
