### ISSUE TITLE
[feat] Allow different embed providers

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/itchy-ionic#34]
Currently we utilize Turbowarp for actually rendering Scratch projects, which provides its own cloud variable server and Javascript-compiling engine rather than running in a VM like Scratch (.mit.edu) does.  However, it might be nice to allow users a few different embed options like the official Scratch embeds, Turbowarp, or others.

**Comment by locness3** [comment]
![](https://i.redd.it/ocwkq2k400i51.jpg)

**Comment by micahlt** [comment]
This is actually something that would be super easy to add.  I'll work on it this afternoon.

**Comment by micahlt** [comment]
I've run into a styling issue - while TurboWarp embeds are transparent, Scratch embeds have a white background that can't be changed.

**Comment by locness3** [comment]
Yes.

**Comment by micahlt** [comment]
It's worth noting that this issue and #35 are mutually exclusive - if we integrate TurboWarp's engine within the app, switching the embed provider would be extremely difficult.  At this point, TurboWarp is stable enough that I'm not sure using the vanilla Scratch embed is beneficial at all.  Thoughts @locness3?

**Comment by locness3** [comment]
> if we integrate TurboWarp's engine within the app, switching the embed provider would be extremely difficult.

nah, turbowarp could be integrated as a separate web page loaded in an iframe, that would be part of the application bundle instead of being loaded from the internet

**Comment by micahlt** [comment]
Ah, I see.  Will that not drastically increase Itchy's download size?

**Comment by locness3** [comment]
> increase Itchy's download size

~~Who cares?~~

For a real answer, it will probably make it the current size + what you download when you visit the TurboWarp website (or use the iframe) - except you likely won't download it as often.

**Comment by micahlt** [comment]
I personally will be fine - my PC is more than equipped to handle it.  So it does look like this is feasible, but still not a massive benefit at the moment so we'll keep it in the backlog.

**Comment by micahlt** [comment]
As there are no benefits to this and it increases the complexity of the app, I'm going to go ahead and close this.  If we get feature requests for this then I might re-open it.
