### ISSUE TITLE
Show which messages are read or unread and allow marking as read

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-ionic#38]

**Comment by micahlt** [comment]
![image](https://user-images.githubusercontent.com/28816297/145688323-4c7e6783-4f7f-4f6a-b65e-7d510a0f87d9.png)

> Show which messages are read or unread

This feature already exists.  In the screenshot below, see how the read message doesn't have the blue dot at the top right of the avatar image.  

> allow marking as read

This does need to be done - I'll work on it 👍

**Comment by locness3** [comment]
> In the screenshot below, see how the read message doesn't have the blue dot at the top right of the avatar image.

They are not distinguishable enough, IMO.

**Comment by micahlt** [comment]
> > In the screenshot below, see how the read message doesn't have the blue dot at the top right of the avatar image.
> 
> They are not distinguishable enough, IMO.

What would you recommend?

**Comment by locness3** [comment]
A blue (primary color) backgrorund, just like on the Scratch website.

**Comment by micahlt** [comment]
Done in my fork (c60e72f539e8ca9bb5d73d5ddcff93229871831a), but I won't close this issue until I merge into this repository.

**Comment by micahlt** [comment]
Resolved in 4f512184c6c7b9dc463d1a52ec16a5031c0c2647 except for marking as read.  From my experimentation with the Scratch API, that's something that will probably have to be done in [micahlt/itchy-api](https://github.com/micahlt/itchy-api), so I'm closing this issue for now.

**Comment by locness3** [comment]
> that's something that will probably have to be done in [micahlt/itchy-api](https://github.com/micahlt/itchy-api)

I assume this means it requires authentication - IMO itchy-api should not be dealing with authenticated actions.

**Comment by micahlt** [comment]
Nope, it means that I've tried doing it on-device and simply can't get it to work since Capacitor's HTTP plugin doesn't act perfectly.  

> itchy-api should not be dealing with authenticated actions

That's the way I'd prefer it too, but I've spent literal hours trying to make Capacitor HTTP work right and I just can't.

**Comment by locness3** [comment]
> Capacitor's HTTP plugin doesn't act perfectly.

Get in touch with the developers.
