### ISSUE TITLE
Do not vibrate when tapping a bottom tab

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-ionic#39]

**Comment by micahlt** [comment]
Why?

**Comment by locness3** [comment]
When tapping a tab in the bottom tab bar on an android device, it makes the device vibrate a bit.
I don't know what's responsible for it, but this is not expected behavior - no other android app, to my knowledge does this.

**Comment by micahlt** [comment]
This was intentional - I figured that some haptics would give the app a more native feel, but I see what you mean.  They'll be removed in my next PR.

**Comment by micahlt** [comment]
Fixed in 4f512184c6c7b9dc463d1a52ec16a5031c0c2647.
