### ISSUE TITLE
Security vuln buildup

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/itchy-ionic#41]
We're to the point where there are now over 16 Dependabot-recognized security vulnerabilities and many, many more when `npm audit` is run.  Simply trying `npm audit fix` doesn't work.  At some point either me or someone else is going to have to dedicate enough time to at least looking into the high-risk vulnerabilities and ensure that they don't affect end users.  Thoughts @locness3?

**Comment by locness3** [comment]
I have not looked at the alerts yet but I bet almost all of these do not affect app usage directly. Please make sure to read [this](https://overreacted.io/npm-audit-broken-by-design/)

**Comment by micahlt** [comment]
Looks like an interesting article, will read.  I'm assuming that most of these are in devDependencies right now, but I'm not entirely sure which is why I said

> ensure that they don't affect end users

**Comment by micahlt** [comment]
Found the option to create Dependabot security updates - about to merge a bunch of them.

**Comment by micahlt** [comment]
No reason not to upgrade if upgrades are available.  But just running `npm audit --production` on my local machine there are only six moderate vulnerabilities in production.  I'll do my best to take care of those.

**Comment by locness3** [comment]
> No reason not to upgrade

[Unless...](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/)

**Comment by micahlt** [comment]
Yeah, yeah, I monitored that whole controversy.  That could happen with any package, not just an update.  Not really an excuse for installing updates as they become available.

**Comment by micahlt** [comment]
Closing this for now since all vulns I've looked at are minor and should not affect end users.
