### ISSUE TITLE
Qwant search limitations

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/itchy-ionic#5]
So far with both `itchy-ionic` and `itchy-cordova` the search has been based on [Qwant](https://www.qwant.com/?l=en)'s open API.  However, just by experimenting it looks like Qwant is severely rate-limiting our requests (from the `micahlt/itchy-api` server).  This is an issue because it results in both 502 and 429 error codes, and of course prevents the user from searching.  

The only solution I can think of would be to move back to Scratch's default search API.  Thoughts?

**Comment by locness3** [comment]
We should use the Scratch API for projects and studios, and qwant's for the rest.

**Comment by micahlt** [comment]
@locness3 So you're suggesting different searches for specific categories?  I'd envisioned a single search for everything...

**Comment by locness3** [comment]
The itchy-api server could handle these different searches with a unified api

**Comment by micahlt** [comment]
@locness3 ah, yes!  That's a good idea.  The only issue to surmount there would be correctly ranking results, but I bet we could figure it out.  Speaking of `micahlt/itchy-api`, I really should move that repository to the SC4 organization.

**Comment by locness3** [comment]
AFAIK Qwant rates users results well, if you filter out useless results.
[Have a look here](https://codepen.io/Locness/pen/yLOjxQL) if you didn't already

**Comment by monitrr** [comment]
Google Enhanced Search?

**Comment by locness3** [comment]
No, Google's Enhanced search is for searching content on the website you put it on; makes no sense being in a mobile app in addition to being a google crap

**Comment by monitrr** [comment]
:/

**Comment by micahlt** [comment]
Plus Enhanced Search isn't really free.  We're looking to spend as _little_ money as possible here.

**Comment by micahlt** [comment]
Once PR #36 is merged, this issue will be closed since we're switching over to a custom search engine that uses the Scratch API.

**Comment by locness3** [comment]
> I really should move that repository to the SC4 organization.

Or move itchy-ionic to your personal account. SC4 is dead.

**Comment by micahlt** [comment]
> > I really should move that repository to the SC4 organization.
> 
> Or move itchy-ionic to your personal account. SC4 is dead.

As I've started multiple times, that's not happening.  There's no reason to move the repo.  Itchy has always been the top priority of SC4 anyway, so as long as development of Itchy continues you can't say that SC4 is dead...

**Comment by locness3** [comment]
Define SC4 in a sentence.

**Comment by micahlt** [comment]
> Define SC4 in a sentence.

A project to build reliable, beautifully designed applications to access the Scratch community, completely open-source and maintained by members of the community.

**Comment by locness3** [comment]
Okay. Well it seems like the whole "community" has lost any interest.

**Comment by micahlt** [comment]
> Okay. Well it seems like the whole "community" has lost any interest.

The development community, maybe.  However, interest on Scratch is at a peak right now, as I just recently shared a promotional project.  If SC4 can't be a community of devs, it can be a community of users.

**Comment by micahlt** [comment]
Resolved by moving away from Qwant search in 4de17021248fc096948f2f52b1c26836ab06655e.
