### ISSUE TITLE
[bug] Emojis in comments don't work

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/itchy-ionic#57]
In the comments, Scratch emojis appear as broken images.  This should be relatively easy to fix - we just have to add the images in the proper location.  We could possibly get the emojis from ScratchAddons.

**Comment by locness3** [comment]
Are you refering to [these](https://en.scratch-wiki.info/wiki/Scratch_Emojis#History)?

**Comment by micahlt** [comment]
Those are the ones!

**Comment by micahlt** [comment]
#58 will resolve this issue.
