### ISSUE TITLE
[bug] turbowarp not syncing with darkmode

### ISSUE THREAD

**Issue by LES-11** [Scratch-Client-4/itchy-ionic#59]
1.  Turbowarp fullscreen button not syncing with dark mode (image 1)
2.  Background and top bar (area around green flag, stop button, etc.) not syncing with darkmode while in fullscreen (image 2)

image 1
![20220403_201649](https://user-images.githubusercontent.com/75516401/161677354-c0821275-f294-4105-a86a-c4fd70f542f2.jpg)
image 2
![20220403_201807](https://user-images.githubusercontent.com/75516401/161677399-9b86f6b1-834e-44fa-8277-763ad48f3fcc.jpg)

**Comment by locness3** [comment]
Turbowarp is loaded from turbowarp.org, so I'm not sure there's much we can do here unless we include turbowarp within the app (see also #35 )

THank you very much for contributing, by the way.

**Comment by LES-11** [comment]
yea np (sorry for the late reply) 
i wasnt sure if that was a turbowarp issue but scratchaddons has the same issue while using dark mode so it probably is

**Comment by micahlt** [comment]
@locness3 is right here - this is out of our control unless #35 is worked on, which is not currently feasible due to my technical knowledge of Scratch's compiler, VM, and GUI.  Closing for now.
