### ISSUE TITLE
[feat] Make haptics optional

### ISSUE THREAD

**Issue by pufferfish101007** [Scratch-Client-4/itchy-ionic#69]
I'm not a big fan of haptics - I find them annoying & unnecessary, and they detract from the experience. It'd be great if there was a setting to disable haptics, and simply not run `vibrate` functions.

**Comment by micahlt** [comment]
I can totally add this - will be in the next update!

(also issue #69 - nice)

**Comment by locness3** [comment]
Tbh, I don't think it needs to be a setting, but just not be used at all.

**Comment by locness3** [comment]
> Tbh, I don't think it needs to be a setting, but just not be used at all.

@micahlt do you have a final take on this, so that the change can be made?

**Comment by micahlt** [comment]
Whoops, meant to resolve this already - it was added as an option in the latest version.

**Comment by micahlt** [comment]
Resolved by 4217658f67ff92c29503a01fe7a2ba73e47eebaa.
