### ISSUE TITLE
[feat] Turn "force dark mode" to a dropdown

### ISSUE THREAD

**Issue by lankybox02** [Scratch-Client-4/itchy-ionic#70]
Instead of a "force dark mode" switch, there could be a dropdown where you cna select `system theme`, `dark mode` and `light mode`.

**Comment by micahlt** [comment]
This has been the plan for a while, it just hasn't been implemented since Ionic doesn't provide a native dropdown element - it'll have to be from scratch.

**Comment by locness3** [comment]
> Ionic doesn't provide a native dropdown element

Oof.

**Comment by locness3** [comment]
> Ionic doesn't provide a native dropdown element

@micahlt It actually does : https://ionicframework.com/docs/api/select

**Comment by micahlt** [comment]
Yep - found that!  This was also added in the latest version of Itchy.

**Comment by micahlt** [comment]
Resolved by 4217658f67ff92c29503a01fe7a2ba73e47eebaa.
